[package]
name = "hyper-mcp"
version = "0.1.0"
edition = "2024"
authors = ["Tuan Anh Tran <me@tuananh.org>"]
description = " A fast, secure MCP server that extends its capabilities through WebAssembly plugins"
keywords = ["rust", "ai", "mcp", "cli"]
categories = ["command-line-utilities"]
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/tuananh/hyper-mcp"
homepage = "https://github.com/tuananh/hyper-mcp"
documentation = "https://github.com/tuananh/hyper-mcp"

[dependencies]
tokio = { version = "1.44", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
toml = "0.8"
reqwest = { version = "0.12", features = ["json"] }
base64 = "0.22.1"
anyhow = "1.0.97"
extism = "1.10.0"
rpc-router = "0.1.3"
url = { version = "2.5.4", features = ["serde"] }
maplit = "1.0.2"
sha2 = "0.10.8"
hex = "0.4.3"
oci-client = "0.14.0"
tar = "0.4.44"
flate2 = "1.1.0"
clap = { version = "4.5.34", features = ["derive", "env"] }
dirs = "6.0"
docker_credential = "1.3.1"
log = "0.4.27"
env_logger = "0.11.7"
chrono = "0.4.40"
tree_magic_mini = "3.0.3"
jsonschema = "0.17"
lazy_static = "1.4"

[[bin]]
name = "hyper-mcp"
path = "src/main.rs"
