---
plugins:
  time:
    url: oci://ghcr.io/tuananh/time-plugin:latest
  qr-code:
    url: oci://ghcr.io/tuananh/qrcode-plugin:latest
  hash:
    url: oci://ghcr.io/tuananh/hash-plugin:latest
  myip:
    url: oci://ghcr.io/tuananh/myip-plugin:latest
    runtime_config:
      allowed_hosts:
        - "1.1.1.1"
      cross_plugin_tools:
        - "get_ip"
  fetch:
    url: oci://ghcr.io/tuananh/fetch-plugin:latest
    runtime_config:
      allowed_hosts:
        - "*"
      cross_plugin_tools:
        - "http_client"
        - "url_validator"
  utilities:
    url: oci://ghcr.io/tuananh/utility-plugin:latest
    runtime_config:
      cross_plugin_tools:
        - "json_parser"
        - "base64_encoder"
        - "logger"
